INSERT INTO cities(id,name,country_a3_iso_code) VALUES (1,'Düsseldorf','DEU');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (2,'Frankfurt am Main','DEU');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (3,'Barcelona','ESP');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (4,'Madrid','ESP');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (5,'Paris','FRA');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (6,'Marseille','FRA');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (7,'Eindhoven','NLD');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (8,'Amsterdam','NLD');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (9,'Porto','PRT');
INSERT INTO cities(id,name,country_a3_iso_code) VALUES (10,'Lisbon','PRT');
