INSERT INTO airports(iata,name,city_id) VALUES ('AMS','Amsterdam Schiphol Airport',8);
INSERT INTO airports(iata,name,city_id) VALUES ('BCN','Barcelona–El Prat Airport',3);
INSERT INTO airports(iata,name,city_id) VALUES ('CDG','Charles de Gaulle Airport',5);
INSERT INTO airports(iata,name,city_id) VALUES ('DUS','Düsseldorf Airport',1);
INSERT INTO airports(iata,name,city_id) VALUES ('EIN','Eindhoven Airport',7);
INSERT INTO airports(iata,name,city_id) VALUES ('FRA','Frankfurt Airport',2);
INSERT INTO airports(iata,name,city_id) VALUES ('LIS','Lisbon Intl. Airport Humberto Delgado',10);
INSERT INTO airports(iata,name,city_id) VALUES ('MAD','Madrid–Barajas Airport',4);
INSERT INTO airports(iata,name,city_id) VALUES ('MGL','Düsseldorf Mönchengladbach Airport',1);
INSERT INTO airports(iata,name,city_id) VALUES ('MRS','Marseille Provence Airport',6);
INSERT INTO airports(iata,name,city_id) VALUES ('OPO','Francisco Sá Carneiro Airport',9);
INSERT INTO airports(iata,name,city_id) VALUES ('ORY','Orly Airport',5);